var searchData=
[
  ['randgen_0',['RandGen',['../class_rand_gen.html',1,'']]],
  ['random_1',['Random',['../classtesting_1_1internal_1_1_random.html',1,'testing::internal']]],
  ['random_5fseed_20unittest_3a_3arandom_5fseed_2',['random_seed {#UnitTest::random_seed}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md317',1,'']]],
  ['randomgentestharness_3',['RandomGenTestHarness',['../class_random_gen_test_harness.html',1,'']]],
  ['rangegenerator_4',['RangeGenerator',['../classtesting_1_1internal_1_1_range_generator.html',1,'testing::internal']]],
  ['rawbytesprinter_5',['RawBytesPrinter',['../structtesting_1_1internal_1_1_raw_bytes_printer.html',1,'testing::internal']]],
  ['re_6',['RE',['../classtesting_1_1internal_1_1_r_e.html',1,'testing::internal']]],
  ['readfile_7',['ReadFile',['../classupload_1_1_subversion_v_c_s.html#a601ffb1146763196a01ee546294248f2',1,'upload.SubversionVCS.ReadFile()'],['../namespacecpp_1_1utils.html#a6c7c7f6290e60b50b063b8ac7f6e9eec',1,'cpp.utils.ReadFile()']]],
  ['readme_20follows_8',['ORIGINAL README FOLLOWS',['../md_cmake_2sdl2-glj_2_r_e_a_d_m_e.html#autotoc_md438',1,'']]],
  ['real_20object_9',['Delegating Calls to a Real Object',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md126',1,'']]],
  ['real_20object_20is_20fine_20what_20can_20be_20wrong_10',['I get a heapcheck failure when using a mock object, but using a real object is fine. What can be wrong?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md188',1,'']]],
  ['real_20object_20is_20invoked_20instead_20what_20s_20the_20problem_11',['When I call a method on my mock object, the method for the real object is invoked instead. What&apos;s the problem?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md181',1,'']]],
  ['realmain_12',['RealMain',['../namespaceupload.html#a7cfc90ec8769d2c5d7fd0f4ca70ab028',1,'upload']]],
  ['reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_13',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md190',1,'']]],
  ['receivedpacket_14',['ReceivedPacket',['../class_received_packet.html',1,'']]],
  ['recipes_20on_20using_20gmock_15',['Misc Recipes on Using gMock',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md159',1,'']]],
  ['recordproperty_20test_3a_3arecordproperty_16',['RecordProperty {#Test::RecordProperty}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md283',1,'']]],
  ['redundant_17',['I have a failed test where gMock tells me TWICE that a particular expectation is not satisfied. Isn&apos;t this redundant?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md187',1,'']]],
  ['reference_18',['Reference',['../md_build_2__deps_2googletest-src_2docs_2reference_2actions.html',1,'Actions Reference'],['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html',1,'Assertions Reference'],['../md_build_2__deps_2googletest-src_2docs_2reference_2matchers.html',1,'Matchers Reference'],['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html',1,'Mocking Reference'],['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html',1,'Testing Reference']]],
  ['references_20from_20mock_20methods_19',['Returning References from Mock Methods',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md147',1,'']]],
  ['references_20to_20some_20static_20const_20member_20variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_20',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md88',1,'']]],
  ['register_5ftyped_5ftest_5fsuite_5fp_21',['REGISTER_TYPED_TEST_SUITE_P',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#REGISTER_TYPED_TEST_SUITE_P',1,'']]],
  ['registering_20tests_20programmatically_22',['Registering tests programmatically',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md53',1,'']]],
  ['registertest_23',['RegisterTest',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#RegisterTest',1,'']]],
  ['regular_20expression_20syntax_24',['Regular Expression Syntax',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md31',1,'']]],
  ['related_20macros_3a_25',['Related macros:',['../md_build_2__deps_2googletest-src_2googlemock_2include_2gmock_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md380',1,'Flag related macros:'],['../md_build_2__deps_2googletest-src_2googletest_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md389',1,'Flag related macros:'],['../md_build_2dist_2include_2gmock_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md426',1,'Flag related macros:'],['../md_build_2dist_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md431',1,'Flag related macros:']]],
  ['related_20open_20source_20projects_26',['Related Open Source Projects',['../md_build_2__deps_2googletest-src_2_r_e_a_d_m_e.html#autotoc_md422',1,'']]],
  ['relationtosourcecopy_27',['RelationToSourceCopy',['../structtesting_1_1internal_1_1_relation_to_source_copy.html',1,'testing::internal']]],
  ['relationtosourcereference_28',['RelationToSourceReference',['../structtesting_1_1internal_1_1_relation_to_source_reference.html',1,'testing::internal']]],
  ['release_201_2010_20x_29',['Release 1.10.x',['../md_build_2__deps_2googletest-src_2_r_e_a_d_m_e.html#autotoc_md412',1,'']]],
  ['release_20testeventlisteners_3a_3arelease_30',['Release {#TestEventListeners::Release}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md351',1,'']]],
  ['release_5fdocs_31',['release_docs',['../namespacerelease__docs.html',1,'']]],
  ['removeconstfromkey_32',['RemoveConstFromKey',['../structtesting_1_1internal_1_1_remove_const_from_key.html',1,'testing::internal']]],
  ['removeconstfromkey_3c_20std_3a_3apair_3c_20const_20k_2c_20v_20_3e_20_3e_33',['RemoveConstFromKey&lt; std::pair&lt; const K, V &gt; &gt;',['../structtesting_1_1internal_1_1_remove_const_from_key_3_01std_1_1pair_3_01const_01_k_00_01_v_01_4_01_4.html',1,'testing::internal']]],
  ['removelocations_34',['RemoveLocations',['../namespacegmock__output__test.html#a59c40167b074a2ef04aecc79a0273f13',1,'gmock_output_test']]],
  ['removememoryaddresses_35',['RemoveMemoryAddresses',['../namespacegmock__output__test.html#ac16c3c4b4875becf250dd73beb381a82',1,'gmock_output_test']]],
  ['removereportheaderandfooter_36',['RemoveReportHeaderAndFooter',['../namespacegmock__output__test.html#acb06643e5e0d0eb85a3bc067e09e56f9',1,'gmock_output_test']]],
  ['removetestnamesofleakedmocks_37',['RemoveTestNamesOfLeakedMocks',['../namespacegmock__output__test.html#ad0a9e9474fb8cb1729c20bc51222c46e',1,'gmock_output_test']]],
  ['rendermanager_38',['RenderManager',['../class_render_manager.html',1,'']]],
  ['repeating_20the_20tests_39',['Repeating the Tests',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md66',1,'']]],
  ['replication_20wrapper_40',['Cross Platform Replication Wrapper',['../md__r_e_a_d_m_e.html',1,'']]],
  ['replicationcommand_41',['ReplicationCommand',['../struct_replication_command.html',1,'']]],
  ['replicationmanagerclient_42',['ReplicationManagerClient',['../class_replication_manager_client.html',1,'']]],
  ['replicationmanagerserver_43',['ReplicationManagerServer',['../class_replication_manager_server.html',1,'']]],
  ['report_44',['Report',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md74',1,'Generating a JSON Report'],['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md73',1,'Generating an XML Report']]],
  ['reportable_5fdisabled_5ftest_5fcount_20testsuite_3a_3areportable_5fdisabled_5ftest_5fcount_45',['reportable_disabled_test_count {#TestSuite::reportable_disabled_test_count}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md292',1,'']]],
  ['reportable_5fdisabled_5ftest_5fcount_20unittest_3a_3areportable_5fdisabled_5ftest_5fcount_46',['reportable_disabled_test_count {#UnitTest::reportable_disabled_test_count}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md325',1,'']]],
  ['reportable_5ftest_5fcount_20testsuite_3a_3areportable_5ftest_5fcount_47',['reportable_test_count {#TestSuite::reportable_test_count}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md294',1,'']]],
  ['reportable_5ftest_5fcount_20unittest_3a_3areportable_5ftest_5fcount_48',['reportable_test_count {#UnitTest::reportable_test_count}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md327',1,'']]],
  ['reported_49',['Controlling How Failures Are Reported',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md75',1,'']]],
  ['require_20the_20entire_20test_20suite_20instead_20of_20individual_20tests_20to_20be_20named_20deathtest_20when_20it_20uses_20assert_5fdeath_50',['Why does googletest require the entire test suite, instead of individual tests, to be named *DeathTest when it uses ASSERT_DEATH?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md102',1,'']]],
  ['requirements_20for_20contributors_51',['Requirements for Contributors',['../md_build_2__deps_2googletest-src_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md7',1,'']]],
  ['requirements_20should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_52',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md84',1,'']]],
  ['requires_53',['Requires',['../classcpp_1_1ast_1_1_node.html#aec63b7dc43a288117d017baa9d042983',1,'cpp.ast.Node.Requires()'],['../classcpp_1_1ast_1_1_expr.html#a704c0220f8dc7f49607d6af3f3744cf9',1,'cpp.ast.Expr.Requires()'],['../classcpp_1_1ast_1_1_parameter.html#a6514b2e10c1818003d6df7e4e8385eb8',1,'cpp.ast.Parameter.Requires()'],['../classcpp_1_1ast_1_1_variable_declaration.html#a72eae8975219cb7ba0e989ceb2be7ac0',1,'cpp.ast.VariableDeclaration.Requires()'],['../classcpp_1_1ast_1_1_typedef.html#ad94253075cea5a5110bf5e9b8fe0ee61',1,'cpp.ast.Typedef.Requires()'],['../classcpp_1_1ast_1_1_class.html#ac1b332bf3c76a5e5e4b204200846cbd0',1,'cpp.ast.Class.Requires()'],['../classcpp_1_1ast_1_1_function.html#a6bfa2b0841e15075b951aa9330603ab5',1,'cpp.ast.Function.Requires()']]],
  ['resetting_20a_20mock_54',['Verifying and Resetting a Mock',['../md_build_2__deps_2googletest-src_2docs_2gmock__cheat__sheet.html#autotoc_md114',1,'']]],
  ['resources_20between_20tests_20in_20the_20same_20test_20suite_55',['Sharing Resources Between Tests in the Same Test Suite',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md43',1,'']]],
  ['restricting_20the_20type_20of_20an_20argument_20or_20parameter_20in_20an_20action_56',['Restricting the Type of an Argument or Parameter in an ACTION',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md175',1,'']]],
  ['result_57',['Ignoring an Action&apos;s Result',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md155',1,'']]],
  ['result_20of_20a_20function_20functor_20or_20callback_58',['Matching the Result of a Function, Functor, or Callback',['../md_build_2__deps_2googletest-src_2docs_2reference_2matchers.html#autotoc_md257',1,'']]],
  ['result_20testinfo_3a_3aresult_59',['result {#TestInfo::result}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md312',1,'']]],
  ['retires_60',['Controlling When an Expectation Retires',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md145',1,'']]],
  ['retiresonsaturation_20expect_5fcall_20retiresonsaturation_61',['RetiresOnSaturation {#EXPECT_CALL.RetiresOnSaturation}',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#autotoc_md269',1,'']]],
  ['return_62',['Return',['../classcpp_1_1ast_1_1_return.html',1,'cpp::ast']]],
  ['return_20a_20value_20what_20s_20going_20on_63',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md94',1,'']]],
  ['return_20type_64',['Setting the Default Value for a Return Type',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#DefaultValue',1,'']]],
  ['return_20type_20specified_20what_20does_20it_20mean_65',['I use SetArgPointee() in WillOnce(), but gcc complains about &quot;conflicting return type specified&quot;. What does it mean?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md197',1,'']]],
  ['return_20value_20when_20i_20call_20run_5fall_5ftests_20why_66',['My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md93',1,'']]],
  ['returnaction_67',['ReturnAction',['../classtesting_1_1internal_1_1_return_action.html',1,'testing::internal']]],
  ['returnargaction_68',['ReturnArgAction',['../structtesting_1_1internal_1_1_return_arg_action.html',1,'testing::internal']]],
  ['returning_20a_20value_69',['Returning a Value',['../md_build_2__deps_2googletest-src_2docs_2reference_2actions.html#autotoc_md244',1,'']]],
  ['returning_20live_20values_20from_20mock_20methods_70',['Returning Live Values from Mock Methods',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md148',1,'']]],
  ['returning_20references_20from_20mock_20methods_71',['Returning References from Mock Methods',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md147',1,'']]],
  ['returnnewaction_72',['ReturnNewAction',['../structtesting_1_1internal_1_1_return_new_action.html',1,'testing::internal']]],
  ['returnnullaction_73',['ReturnNullAction',['../classtesting_1_1internal_1_1_return_null_action.html',1,'testing::internal']]],
  ['returnpointeeaction_74',['ReturnPointeeAction',['../structtesting_1_1internal_1_1_return_pointee_action.html',1,'testing::internal']]],
  ['returnrefaction_75',['ReturnRefAction',['../classtesting_1_1internal_1_1_return_ref_action.html',1,'testing::internal']]],
  ['returnrefofcopyaction_76',['ReturnRefOfCopyAction',['../classtesting_1_1internal_1_1_return_ref_of_copy_action.html',1,'testing::internal']]],
  ['returnroundrobinaction_77',['ReturnRoundRobinAction',['../classtesting_1_1internal_1_1_return_round_robin_action.html',1,'testing::internal']]],
  ['returns_20an_20assertionresult_78',['Using a Function That Returns an AssertionResult',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md17',1,'']]],
  ['returnvoidaction_79',['ReturnVoidAction',['../classtesting_1_1internal_1_1_return_void_action.html',1,'testing::internal']]],
  ['rock_80',['Rock',['../class_rock.html',1,'']]],
  ['rockclient_81',['RockClient',['../class_rock_client.html',1,'']]],
  ['rockserver_82',['RockServer',['../class_rock_server.html',1,'']]],
  ['rocktestharness_83',['RockTestHarness',['../class_rock_test_harness.html',1,'']]],
  ['routines_84',['Using Assertions in Sub-routines',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md36',1,'']]],
  ['rsquo_20when_20i_20use_20an_20assertion_20what_20gives_85',['The compiler complains about &amp;lsquo;no match for &apos;operator&lt;&lt;&amp;rsquo;` when I use an assertion. What gives?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md105',1,'']]],
  ['rule_20makes_20writing_20expectations_20awkward_20why_20does_20gmock_20do_20that_86',['The &quot;newer expectations override older ones&quot; rule makes writing expectations awkward. Why does gMock do that?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md189',1,'']]],
  ['run_20a_20binary_87',['Run a binary',['../md_build_2__deps_2googletest-src_2docs_2quickstart-bazel.html#autotoc_md236',1,'Create and run a binary'],['../md_build_2__deps_2googletest-src_2docs_2quickstart-cmake.html#autotoc_md241',1,'Create and run a binary']]],
  ['run_20time_20errors_20about_20invalid_20proto_20descriptors_20when_20using_20tt_20protocolmessageequals_20tt_20help_88',['I got some run-time errors about invalid proto descriptors when using &lt;tt&gt;ProtocolMessageEquals&lt;/tt&gt;. Help!',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md85',1,'']]],
  ['run_5fall_5ftests_89',['RUN_ALL_TESTS',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#RUN_ALL_TESTS',1,'']]],
  ['run_5fall_5ftests_20why_90',['My compiler complains about &quot;ignoring return value&quot; when I call RUN_ALL_TESTS(). Why?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md93',1,'']]],
  ['run_5fwith_5fpath_91',['run_with_path',['../namespacerun__with__path.html',1,'']]],
  ['runandverify_92',['RunAndVerify',['../classgoogletest-break-on-failure-unittest_1_1_g_test_break_on_failure_unit_test.html#aa10728830adf68f6c0fd9e8ff9a3e5a2',1,'googletest-break-on-failure-unittest.GTestBreakOnFailureUnitTest.RunAndVerify()'],['../classgoogletest-filter-unittest_1_1_g_test_filter_unit_test.html#a210d536f4dd4dc5d8ea687747ca8d6d5',1,'googletest-filter-unittest.GTestFilterUnitTest.RunAndVerify()'],['../classgoogletest-list-tests-unittest_1_1_g_test_list_tests_unit_test.html#a181f8f8424ac864380a56f443bd571e7',1,'googletest-list-tests-unittest.GTestListTestsUnitTest.RunAndVerify()'],['../classgoogletest-throw-on-failure-test_1_1_throw_on_failure_test.html#a4438abd96792c91b81e3bae28fc27087',1,'googletest-throw-on-failure-test.ThrowOnFailureTest.RunAndVerify()']]],
  ['runandverifyallowingdisabled_93',['RunAndVerifyAllowingDisabled',['../classgoogletest-filter-unittest_1_1_g_test_filter_unit_test.html#a8ec218a765232f76b13c81f17c8ee11f',1,'googletest-filter-unittest::GTestFilterUnitTest']]],
  ['runandverifywithsharding_94',['RunAndVerifyWithSharding',['../classgoogletest-filter-unittest_1_1_g_test_filter_unit_test.html#a8c4225edcc9ca56e44976fa0d7d84d0b',1,'googletest-filter-unittest::GTestFilterUnitTest']]],
  ['running_20a_20subset_20of_20the_20tests_95',['Running a Subset of the Tests',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md62',1,'']]],
  ['running_20in_20a_20test_96',['How can my code detect if it is running in a test?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md107',1,'']]],
  ['running_20test_20programs_3a_20advanced_20options_97',['Running Test Programs: Advanced Options',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md59',1,'']]],
  ['running_20tests_20in_20emacs_98',['Running Tests in Emacs',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md166',1,'']]],
  ['runs_20out_20of_20memory_20when_20compiling_20it_20what_20can_20i_20do_99',['I have a huge mock class, and Microsoft Visual C++ runs out of memory when compiling it. What can I do?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md198',1,'']]],
  ['runshellwithreturncode_100',['RunShellWithReturnCode',['../namespaceupload.html#ad776c093afe992c8e51eeb3d5c794f72',1,'upload']]],
  ['runtimes_101',['Visual Studio Dynamic vs Static Runtimes',['../md_build_2__deps_2googletest-src_2googletest_2_r_e_a_d_m_e.html#autotoc_md400',1,'']]],
  ['runwithflag_102',['RunWithFlag',['../namespacegtest__help__test.html#a5aa27057b0ddd8f10405b613d6d3b057',1,'gtest_help_test']]]
];
