var searchData=
[
  ['s_20a_20lot_20of_20pain_20to_20specify_20the_20actions_20gmock_20sucks_0',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['s_20argument_1',['How can I perform an arbitrary action on a mock function&apos;s argument?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md192',1,'']]],
  ['s_20argument_20in_20an_20action_2',['How can I delete the mock function&apos;s argument in an action?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md191',1,'']]],
  ['s_20arguments_3',['Selecting an Action&apos;s Arguments',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#SelectingArgs',1,'']]],
  ['s_20behavior_20based_20on_20the_20state_4',['Changing a Mock Object&apos;s Behavior Based on the State',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md150',1,'']]],
  ['s_20c_20test_20framework_5',['Welcome to &lt;strong&gt;GoogleTest&lt;/strong&gt;, Google&apos;s C++ test framework!',['../md_build_2__deps_2googletest-src_2_r_e_a_d_m_e.html#autotoc_md414',1,'']]],
  ['s_20child_20process_20only_20when_20the_20test_20fails_20how_20can_20i_20see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_6',['googletest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md104',1,'']]],
  ['s_20going_20on_7',['My compiler complains that a constructor (or destructor) cannot return a value. What&apos;s going on?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md94',1,'']]],
  ['s_20guide_8',['GoogleTest User&apos;s Guide',['../md_build_2__deps_2googletest-src_2docs_2index.html',1,'']]],
  ['s_20name_9',['Getting the Current Test&apos;s Name',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md54',1,'']]],
  ['s_20result_10',['Ignoring an Action&apos;s Result',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md155',1,'']]],
  ['s_20the_20problem_11',['When I call a method on my mock object, the method for the real object is invoked instead. What&apos;s the problem?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md181',1,'']]],
  ['s_20type_12',['Using the ACTION Object&apos;s Type',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md177',1,'']]],
  ['s_20wrong_13',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md88',1,'']]],
  ['said_20otherwise_14',['All Expectations Are Sticky (Unless Said Otherwise)',['../md_build_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#StickyExpectations',1,'']]],
  ['same_20data_20configuration_20for_20multiple_20tests_15',['Test Fixtures: Using the Same Data Configuration for Multiple Tests',['../md_build_2__deps_2googletest-src_2docs_2primer.html#same-data-multiple-tests',1,'']]],
  ['same_20test_20fixture_20logic_20do_20i_20have_20to_20define_20a_20new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_16',['I have several test suites which share the same test fixture logic, do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md96',1,'']]],
  ['same_20test_20suite_17',['Sharing Resources Between Tests in the Same Test Suite',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md43',1,'']]],
  ['samples_18',['Googletest Samples',['../md_build_2__deps_2googletest-src_2docs_2samples.html',1,'']]],
  ['sanitizer_20integration_19',['Sanitizer Integration',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md79',1,'']]],
  ['satisfied_20isn_20t_20this_20redundant_20',['I have a failed test where gMock tells me TWICE that a particular expectation is not satisfied. Isn&apos;t this redundant?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md187',1,'']]],
  ['satisfied_20what_20should_20i_20do_21',['I can&apos;t figure out why gMock thinks my expectations are not satisfied. What should I do?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md184',1,'']]],
  ['satisfy_20some_20common_20requirements_20should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_22',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md84',1,'']]],
  ['saveargaction_23',['SaveArgAction',['../structtesting_1_1internal_1_1_save_arg_action.html',1,'testing::internal']]],
  ['saveargpointeeaction_24',['SaveArgPointeeAction',['../structtesting_1_1internal_1_1_save_arg_pointee_action.html',1,'testing::internal']]],
  ['scoped_5ftrace_25',['SCOPED_TRACE',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#SCOPED_TRACE',1,'']]],
  ['scopedmocklog_20tt_20spit_20out_20tons_20of_20messages_20is_20it_20a_20gmock_20bug_26',['My program crashed and &lt;tt&gt;ScopedMockLog&lt;/tt&gt; spit out tons of messages. Is it a gMock bug?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md185',1,'']]],
  ['scopedprematureexitfile_27',['ScopedPrematureExitFile',['../classtesting_1_1internal_1_1_scoped_premature_exit_file.html',1,'testing::internal']]],
  ['scopedtrace_28',['ScopedTrace',['../classtesting_1_1_scoped_trace.html',1,'testing::ScopedTrace'],['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#ScopedTrace',1,'ScopedTrace']]],
  ['sdl2_20cmake_20modules_29',['SDL2 CMake modules',['../md_cmake_2sdl2-glj_2_r_e_a_d_m_e.html',1,'']]],
  ['see_20the_20log_20messages_20when_20the_20death_20test_20succeeds_30',['googletest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md104',1,'']]],
  ['seems_20lost_20after_20the_20death_20test_20finishes_20why_31',['My death test modifies some state, but the change seems lost after the death test finishes. Why?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md86',1,'']]],
  ['seems_20pretty_20tedious_32',['I have several test suites which share the same test fixture logic, do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md96',1,'']]],
  ['seg_20faults_20how_20do_20i_20fix_20it_33',['My death test hangs (or seg-faults). How do I fix it?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md91',1,'']]],
  ['selecting_20an_20action_20s_20arguments_34',['Selecting an Action&apos;s Arguments',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#SelectingArgs',1,'']]],
  ['selecting_20between_20overloaded_20functions_35',['Selecting Between Overloaded Functions',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#SelectOverload',1,'']]],
  ['selecting_20tests_36',['Selecting Tests',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md60',1,'']]],
  ['send_37',['Send',['../classupload_1_1_abstract_rpc_server.html#a9785441d36f25c0d36a9e6f5593e7177',1,'upload::AbstractRpcServer']]],
  ['separate_20tt_20test_20foo_20bar_20tt_20test_20methods_20defined_20in_20different_20namespaces_38',['Is it OK if I have two separate &lt;tt&gt;TEST(Foo, Bar)&lt;/tt&gt; test methods defined in different namespaces?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md109',1,'']]],
  ['separateinstancetest_39',['SeparateInstanceTest',['../class_separate_instance_test.html',1,'']]],
  ['sequence_40',['Sequence',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#Sequence',1,'']]],
  ['sequencetestinglistener_41',['SequenceTestingListener',['../class_sequence_testing_listener.html',1,'']]],
  ['server_42',['Server',['../class_server.html',1,'']]],
  ['server_20error_20try_20again_43',['Server Error - try again.',['../classupload_1_1_http_rpc_server.html#autotoc_md407',1,'']]],
  ['set_20its_20behavior_20using_20on_5fcall_20would_20it_20be_20reasonable_20not_20to_20show_20the_20warning_20in_20this_20case_44',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md190',1,'']]],
  ['set_20up_20a_20bazel_20workspace_45',['Set up a Bazel workspace',['../md_build_2__deps_2googletest-src_2docs_2quickstart-bazel.html#autotoc_md235',1,'']]],
  ['set_20up_20a_20project_46',['Set up a project',['../md_build_2__deps_2googletest-src_2docs_2quickstart-cmake.html#autotoc_md240',1,'']]],
  ['set_20up_20and_20tear_20down_47',['Global Set-Up and Tear-Down',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md44',1,'']]],
  ['setargpointee_20in_20willonce_20but_20gcc_20complains_20about_20conflicting_20return_20type_20specified_20what_20does_20it_20mean_48',['I use SetArgPointee() in WillOnce(), but gcc complains about &quot;conflicting return type specified&quot;. What does it mean?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md197',1,'']]],
  ['setargrefereeaction_49',['SetArgRefereeAction',['../structtesting_1_1internal_1_1_set_arg_referee_action.html',1,'testing::internal']]],
  ['setargumentpointeeaction_50',['SetArgumentPointeeAction',['../structtesting_1_1internal_1_1_set_argument_pointee_action.html',1,'testing::internal']]],
  ['setarrayargumentaction_51',['SetArrayArgumentAction',['../structtesting_1_1internal_1_1_set_array_argument_action.html',1,'testing::internal']]],
  ['setenvvar_52',['SetEnvVar',['../namespacegtest__test__utils.html#abece99ff6c6b9c882ab12c15793898bf',1,'gtest_test_utils']]],
  ['seterrnoandreturnaction_53',['SetErrnoAndReturnAction',['../classtesting_1_1internal_1_1_set_errno_and_return_action.html',1,'testing::internal']]],
  ['setting_54',['Using pkg-config in a cross-compilation setting',['../md_build_2__deps_2googletest-src_2docs_2pkgconfig.html#autotoc_md219',1,'']]],
  ['setting_20default_20actions_55',['Setting Default Actions',['../md_build_2__deps_2googletest-src_2docs_2gmock__cheat__sheet.html#OnCall',1,'']]],
  ['setting_20expectations_56',['Setting Expectations',['../md_build_2__deps_2googletest-src_2docs_2gmock__cheat__sheet.html#ExpectCall',1,'Setting Expectations'],['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md142',1,'Setting Expectations'],['../md_build_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#autotoc_md208',1,'Setting Expectations']]],
  ['setting_20the_20default_20actions_20for_20a_20mock_20method_57',['Setting the Default Actions for a Mock Method',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md151',1,'']]],
  ['setting_20the_20default_20value_20for_20a_20return_20type_58',['Setting the Default Value for a Return Type',['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#DefaultValue',1,'']]],
  ['setup_59',['setUp',['../classgoogletest-filter-unittest_1_1_g_test_filter_unit_test.html#a80e82b6c777fbbf575ad83cb8d2ae56c',1,'googletest-filter-unittest::GTestFilterUnitTest']]],
  ['setup_60',['Setup',['../md_build_2__deps_2googletest-src_2googletest_2_r_e_a_d_m_e.html#autotoc_md396',1,'']]],
  ['setup_20environment_3a_3asetup_61',['SetUp {#Environment::SetUp}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md275',1,'']]],
  ['setup_20function_20is_20not_20called_20why_62',['My SetUp() function is not called. Why?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md95',1,'']]],
  ['setup_20teardown_63',['Should I use the constructor/destructor of the test fixture or SetUp()/TearDown()?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#CtorVsSetUp',1,'']]],
  ['setup_20test_3a_3asetup_64',['SetUp {#Test::SetUp}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md284',1,'']]],
  ['setupenvironment_65',['SetupEnvironment',['../class_setup_environment.html',1,'']]],
  ['setupfailtest_66',['SetupFailTest',['../class_setup_fail_test.html',1,'']]],
  ['setuptestcasetest_67',['SetUpTestCaseTest',['../classtesting_1_1_set_up_test_case_test.html',1,'testing']]],
  ['setuptestsuite_20test_3a_3asetuptestsuite_68',['SetUpTestSuite {#Test::SetUpTestSuite}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md277',1,'']]],
  ['setuptestsuitetest_69',['SetUpTestSuiteTest',['../classtesting_1_1_set_up_test_suite_test.html',1,'testing']]],
  ['setvalue_70',['SetValue',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#SetValue',1,'']]],
  ['several_20test_20suites_20which_20share_20the_20same_20test_20fixture_20logic_20do_20i_20have_20to_20define_20a_20new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_71',['I have several test suites which share the same test fixture logic, do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md96',1,'']]],
  ['share_20the_20same_20test_20fixture_20logic_20do_20i_20have_20to_20define_20a_20new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_72',['I have several test suites which share the same test fixture logic, do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md96',1,'']]],
  ['shared_20library_20dll_73',['As a Shared Library (DLL)',['../md_build_2__deps_2googletest-src_2googletest_2_r_e_a_d_m_e.html#autotoc_md404',1,'']]],
  ['sharing_20actions_74',['Sharing Actions',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md157',1,'']]],
  ['sharing_20matchers_75',['Sharing Matchers',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md141',1,'']]],
  ['sharing_20resources_20between_20tests_20in_20the_20same_20test_20suite_76',['Sharing Resources Between Tests in the Same Test Suite',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md43',1,'']]],
  ['sheet_77',['gMock Cheat Sheet',['../md_build_2__deps_2googletest-src_2docs_2gmock__cheat__sheet.html',1,'']]],
  ['should_20i_20do_78',['I can&apos;t figure out why gMock thinks my expectations are not satisfied. What should I do?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md184',1,'']]],
  ['should_20i_20panic_79',['I got a warning &quot;Uninteresting function call encountered - default action taken..&quot; Should I panic?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md195',1,'']]],
  ['should_20i_20prefer_20test_20fixtures_20over_20global_20variables_80',['Why should I prefer test fixtures over global variables?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md98',1,'']]],
  ['should_20i_20use_20invoke_20or_20implement_20the_20actioninterface_20interface_81',['I want to define a custom action. Should I use Invoke() or implement the ActionInterface interface?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md196',1,'']]],
  ['should_20i_20use_20the_20constructor_20destructor_20of_20the_20test_20fixture_20or_20setup_20teardown_82',['Should I use the constructor/destructor of the test fixture or SetUp()/TearDown()?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#CtorVsSetUp',1,'']]],
  ['should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_83',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md84',1,'']]],
  ['should_20it_20do_84',['Actions: What Should It Do?',['../md_build_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#autotoc_md212',1,'']]],
  ['should_20test_20suite_20names_20and_20test_20names_20not_20contain_20underscore_85',['Why should test suite names and test names not contain underscore?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md82',1,'']]],
  ['should_5frun_20testinfo_3a_3ashould_5frun_86',['should_run {#TestInfo::should_run}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md310',1,'']]],
  ['should_5frun_20testsuite_3a_3ashould_5frun_87',['should_run {#TestSuite::should_run}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md288',1,'']]],
  ['show_20the_20warning_20in_20this_20case_88',['gMock prints a warning when a function without EXPECT_CALL is called, even if I have set its behavior using ON_CALL. Would it be reasonable not to show the warning in this case?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md190',1,'']]],
  ['shuffling_20the_20tests_89',['Shuffling the Tests',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md67',1,'']]],
  ['side_20effects_90',['Matchers must have no side-effects',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#PureMatchers',1,'']]],
  ['side_20effects_91',['Side Effects',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#MockingSideEffects',1,'Mocking Side Effects'],['../md_build_2__deps_2googletest-src_2docs_2reference_2actions.html#autotoc_md245',1,'Side Effects']]],
  ['simple_20matchers_92',['Using Simple Matchers',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md130',1,'']]],
  ['simple_20tests_93',['Simple Tests',['../md_build_2__deps_2googletest-src_2docs_2primer.html#autotoc_md229',1,'']]],
  ['simplifying_20the_20interface_20without_20breaking_20existing_20code_94',['Simplifying the Interface without Breaking Existing Code',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#SimplerInterfaces',1,'']]],
  ['skipentireenvironmenttest_95',['SkipEntireEnvironmentTest',['../classgtest__skip__check__output__test_1_1_skip_entire_environment_test.html',1,'gtest_skip_check_output_test.SkipEntireEnvironmentTest'],['../classgtest__skip__environment__check__output__test_1_1_skip_entire_environment_test.html',1,'gtest_skip_environment_check_output_test.SkipEntireEnvironmentTest']]],
  ['skipped_20testpartresult_3a_3askipped_96',['skipped {#TestPartResult::skipped}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md359',1,'']]],
  ['skipped_20testresult_3a_3askipped_97',['Skipped {#TestResult::Skipped}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md367',1,'']]],
  ['skipped_5ftest_5fcount_20testsuite_3a_3askipped_5ftest_5fcount_98',['skipped_test_count {#TestSuite::skipped_test_count}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md290',1,'']]],
  ['skipped_5ftest_5fcount_20unittest_3a_3askipped_5ftest_5fcount_99',['skipped_test_count {#UnitTest::skipped_test_count}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md323',1,'']]],
  ['skippedtest_100',['SkippedTest',['../class_skipped_test.html',1,'']]],
  ['skipping_20test_20execution_101',['Skipping test execution',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md26',1,'']]],
  ['socketaddress_102',['SocketAddress',['../class_socket_address.html',1,'']]],
  ['socketaddressfactory_103',['SocketAddressFactory',['../class_socket_address_factory.html',1,'']]],
  ['socketaddressfactorytestharness_104',['SocketAddressFactoryTestHarness',['../class_socket_address_factory_test_harness.html',1,'']]],
  ['socketaddresstestharenss_105',['SocketAddressTestHarenss',['../class_socket_address_test_harenss.html',1,'']]],
  ['socketutil_106',['SocketUtil',['../class_socket_util.html',1,'']]],
  ['socketutiltestharness_107',['SocketUtilTestHarness',['../class_socket_util_test_harness.html',1,'']]],
  ['some_20common_20requirements_20should_20i_20use_20typed_20tests_20or_20value_20parameterized_20tests_108',['I need to test that different implementations of an interface satisfy some common requirements. Should I use typed tests or value-parameterized tests?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md84',1,'']]],
  ['some_20run_20time_20errors_20about_20invalid_20proto_20descriptors_20when_20using_20tt_20protocolmessageequals_20tt_20help_109',['I got some run-time errors about invalid proto descriptors when using &lt;tt&gt;ProtocolMessageEquals&lt;/tt&gt;. Help!',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md85',1,'']]],
  ['some_20state_20but_20the_20change_20seems_20lost_20after_20the_20death_20test_20finishes_20why_110',['My death test modifies some state, but the change seems lost after the death test finishes. Why?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md86',1,'']]],
  ['some_20static_20const_20member_20variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_111',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md88',1,'']]],
  ['soon_112',['Coming Soon',['../md_build_2__deps_2googletest-src_2_r_e_a_d_m_e.html#autotoc_md413',1,'']]],
  ['source_20projects_113',['Related Open Source Projects',['../md_build_2__deps_2googletest-src_2_r_e_a_d_m_e.html#autotoc_md422',1,'']]],
  ['special_20customization_20variables_114',['Special customization variables',['../md_cmake_2sdl2-glj_2_r_e_a_d_m_e.html#autotoc_md443',1,'']]],
  ['specified_20what_20does_20it_20mean_115',['I use SetArgPointee() in WillOnce(), but gcc complains about &quot;conflicting return type specified&quot;. What does it mean?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md197',1,'']]],
  ['specify_20the_20actions_20gmock_20sucks_116',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['specifying_20calling_20conventions_20for_20mock_20functions_117',['Specifying Calling Conventions for Mock Functions',['../md_build_2__deps_2googletest-src_2docs_2gmock__cheat__sheet.html#autotoc_md112',1,'']]],
  ['specifying_20names_20for_20value_20parameterized_20test_20parameters_118',['Specifying Names for Value-Parameterized Test Parameters',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md48',1,'']]],
  ['spit_20out_20tons_20of_20messages_20is_20it_20a_20gmock_20bug_119',['My program crashed and &lt;tt&gt;ScopedMockLog&lt;/tt&gt; spit out tons of messages. Is it a gMock bug?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md185',1,'']]],
  ['splitpatch_120',['SplitPatch',['../namespaceupload.html#ace170a709228951af58ac3b49f0a3e15',1,'upload']]],
  ['spritecomponent_121',['SpriteComponent',['../class_sprite_component.html',1,'']]],
  ['stackinterface_122',['StackInterface',['../classtesting_1_1gmock__function__mocker__test_1_1_stack_interface.html',1,'testing::gmock_function_mocker_test']]],
  ['standalone_20cmake_20project_123',['Standalone CMake Project',['../md_build_2__deps_2googletest-src_2googletest_2_r_e_a_d_m_e.html#autotoc_md398',1,'']]],
  ['standard_20version_124',['C++ Standard Version',['../md_build_2__deps_2googletest-src_2googletest_2_r_e_a_d_m_e.html#autotoc_md401',1,'']]],
  ['start_5ftimestamp_20testresult_3a_3astart_5ftimestamp_125',['start_timestamp {#TestResult::start_timestamp}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md372',1,'']]],
  ['start_5ftimestamp_20testsuite_3a_3astart_5ftimestamp_126',['start_timestamp {#TestSuite::start_timestamp}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md300',1,'']]],
  ['start_5ftimestamp_20unittest_3a_3astart_5ftimestamp_127',['start_timestamp {#UnitTest::start_timestamp}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md330',1,'']]],
  ['started_128',['Started',['../md_build_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#autotoc_md202',1,'Getting Started'],['../md_build_2__deps_2googletest-src_2_r_e_a_d_m_e.html#autotoc_md415',1,'Getting Started']]],
  ['state_129',['Changing a Mock Object&apos;s Behavior Based on the State',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md150',1,'']]],
  ['state_20but_20the_20change_20seems_20lost_20after_20the_20death_20test_20finishes_20why_130',['My death test modifies some state, but the change seems lost after the death test finishes. Why?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md86',1,'']]],
  ['statefulnamingfunctor_131',['StatefulNamingFunctor',['../struct_stateful_naming_functor.html',1,'']]],
  ['statefulnamingtest_132',['StatefulNamingTest',['../class_stateful_naming_test.html',1,'']]],
  ['statement_20argument_20in_20assert_5fdeath_20be_133',['What can the statement argument in ASSERT_DEATH() be?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md99',1,'']]],
  ['static_20const_20member_20variables_20but_20i_20did_20define_20them_20in_20the_20class_20body_20what_20s_20wrong_134',['The compiler complains about &quot;undefined references&quot; to some static const member variables, but I did define them in the class body. What&apos;s wrong?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md88',1,'']]],
  ['static_20global_20function_20can_20i_20mock_20it_135',['My code calls a static/global function. Can I mock it?',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md193',1,'']]],
  ['static_20runtimes_136',['Visual Studio Dynamic vs Static Runtimes',['../md_build_2__deps_2googletest-src_2googletest_2_r_e_a_d_m_e.html#autotoc_md400',1,'']]],
  ['staticasserttypeeq_137',['StaticAssertTypeEq',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#StaticAssertTypeEq',1,'']]],
  ['staticasserttypeeqtesthelper_138',['StaticAssertTypeEqTestHelper',['../class_static_assert_type_eq_test_helper.html',1,'']]],
  ['statusupdate_139',['StatusUpdate',['../namespaceupload.html#a68fb71b953a98818b5dfdcfcb90dda07',1,'upload']]],
  ['std_3a_3afunction_140',['Mock std::function',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#MockFunction',1,'']]],
  ['steps_141',['Steps',['../md_build_2__deps_2googletest-src_2docs_2quickstart-bazel.html#autotoc_md237',1,'Next steps'],['../md_build_2__deps_2googletest-src_2docs_2quickstart-cmake.html#autotoc_md242',1,'Next steps']]],
  ['sticky_20unless_20said_20otherwise_142',['All Expectations Are Sticky (Unless Said Otherwise)',['../md_build_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#StickyExpectations',1,'']]],
  ['stlcontainerview_143',['StlContainerView',['../classtesting_1_1internal_1_1_stl_container_view.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20_3a_3astd_3a_3atuple_3c_20elementpointer_2c_20size_20_3e_20_3e_144',['StlContainerView&lt; ::std::tuple&lt; ElementPointer, Size &gt; &gt;',['../classtesting_1_1internal_1_1_stl_container_view_3_01_1_1std_1_1tuple_3_01_element_pointer_00_01_size_01_4_01_4.html',1,'testing::internal']]],
  ['stlcontainerview_3c_20element_5bn_5d_3e_145',['StlContainerView&lt; Element[N]&gt;',['../classtesting_1_1internal_1_1_stl_container_view_3_01_element_0f_n_0e_4.html',1,'testing::internal']]],
  ['stop_20test_20execution_20upon_20first_20failure_146',['Stop test execution upon first failure',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md63',1,'']]],
  ['streamableinglobal_147',['StreamableInGlobal',['../class_streamable_in_global.html',1,'']]],
  ['streamabletemplateinfoo_148',['StreamableTemplateInFoo',['../classfoo_1_1_streamable_template_in_foo.html',1,'foo']]],
  ['streamprinter_149',['StreamPrinter',['../structtesting_1_1internal_1_1internal__stream__operator__without__lexical__name__lookup_1_1_stream_printer.html',1,'testing::internal::internal_stream_operator_without_lexical_name_lookup']]],
  ['strict_20and_20the_20naggy_150',['The Nice, the Strict, and the Naggy',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#NiceStrictNaggy',1,'']]],
  ['strictmock_151',['StrictMock',['../classtesting_1_1_strict_mock.html',1,'testing::StrictMock&lt; MockClass &gt;'],['../md_build_2__deps_2googletest-src_2docs_2reference_2mocking.html#StrictMock',1,'StrictMock']]],
  ['strictmockimpl_152',['StrictMockImpl',['../classtesting_1_1internal_1_1_strict_mock_impl.html',1,'testing::internal']]],
  ['strictmockimpl_3c_20mockclass_20_3e_153',['StrictMockImpl&lt; MockClass &gt;',['../classtesting_1_1internal_1_1_strict_mock_impl.html',1,'testing::internal']]],
  ['string_154',['String',['../classtesting_1_1internal_1_1_string.html',1,'testing::internal']]],
  ['string_20assertions_155',['More String Assertions',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md22',1,'']]],
  ['string_20comparison_156',['String Comparison',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#c-strings',1,'']]],
  ['string_20matchers_157',['String Matchers',['../md_build_2__deps_2googletest-src_2docs_2reference_2matchers.html#autotoc_md254',1,'']]],
  ['stripleadingwhitespace_158',['StripLeadingWhitespace',['../classcpp_1_1gmock__class__test_1_1_test_case.html#ac8d2fe29fe33f8554ef45c89091e5028',1,'cpp::gmock_class_test::TestCase']]],
  ['strong_20googletest_20strong_20google_20s_20c_20test_20framework_159',['Welcome to &lt;strong&gt;GoogleTest&lt;/strong&gt;, Google&apos;s C++ test framework!',['../md_build_2__deps_2googletest-src_2_r_e_a_d_m_e.html#autotoc_md414',1,'']]],
  ['struct_160',['Struct',['../classcpp_1_1ast_1_1_struct.html',1,'cpp::ast']]],
  ['students_161',['For Students',['../md__r_e_a_d_m_e.html#autotoc_md446',1,'']]],
  ['studio_20dynamic_20vs_20static_20runtimes_162',['Visual Studio Dynamic vs Static Runtimes',['../md_build_2__deps_2googletest-src_2googletest_2_r_e_a_d_m_e.html#autotoc_md400',1,'']]],
  ['stuff_20it_20s_20a_20lot_20of_20pain_20to_20specify_20the_20actions_20gmock_20sucks_163',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['style_164',['Style',['../md_build_2__deps_2googletest-src_2_c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md6',1,'']]],
  ['style_20tt_20mock_5fmethodn_20tt_20macros_165',['Old-Style &lt;tt&gt;MOCK_METHODn&lt;/tt&gt; Macros',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md124',1,'']]],
  ['styles_166',['Death Test Styles',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md34',1,'']]],
  ['sub_20routines_167',['Using Assertions in Sub-routines',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md36',1,'']]],
  ['submit_20your_20own_20code_168',['How to become a contributor and submit your own code',['../md_build_2__deps_2googletest-src_2_c_o_n_t_r_i_b_u_t_i_n_g.html',1,'']]],
  ['subprocess_169',['Subprocess',['../classgtest__test__utils_1_1_subprocess.html',1,'gtest_test_utils']]],
  ['subroutines_170',['Asserting on Subroutines',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md40',1,'']]],
  ['subroutines_20with_20an_20exception_171',['Asserting on Subroutines with an exception',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md39',1,'']]],
  ['subset_20of_20the_20tests_172',['Running a Subset of the Tests',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md62',1,'']]],
  ['subversionvcs_173',['SubversionVCS',['../classupload_1_1_subversion_v_c_s.html',1,'upload']]],
  ['succeed_174',['SUCCEED',['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#SUCCEED',1,'']]],
  ['succeeds_175',['googletest prints the LOG messages in a death test&apos;s child process only when the test fails. How can I see the LOG messages when the death test succeeds?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md104',1,'']]],
  ['success_20and_20failure_176',['Success and Failure',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md13',1,'Explicit Success and Failure'],['../md_build_2__deps_2googletest-src_2docs_2reference_2assertions.html#success-failure',1,'Explicit Success and Failure']]],
  ['successful_5ftest_5fcount_20testsuite_3a_3asuccessful_5ftest_5fcount_177',['successful_test_count {#TestSuite::successful_test_count}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md289',1,'']]],
  ['successful_5ftest_5fcount_20unittest_3a_3asuccessful_5ftest_5fcount_178',['successful_test_count {#UnitTest::successful_test_count}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md322',1,'']]],
  ['successful_5ftest_5fsuite_5fcount_20unittest_3a_3asuccessful_5ftest_5fsuite_5fcount_179',['successful_test_suite_count {#UnitTest::successful_test_suite_count}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md318',1,'']]],
  ['successfultest_180',['SuccessfulTest',['../class_successful_test.html',1,'']]],
  ['sucks_181',['My mock object needs to do complex stuff. It&apos;s a lot of pain to specify the actions. gMock sucks!',['../md_build_2__deps_2googletest-src_2docs_2gmock__faq.html#autotoc_md194',1,'']]],
  ['suite_182',['Sharing Resources Between Tests in the Same Test Suite',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md43',1,'']]],
  ['suite_20deathtest_20when_20it_20contains_20both_20death_20tests_20and_20non_20death_20tests_20what_20do_20i_20do_183',['But I don&apos;t like calling my entire test suite *DeathTest when it contains both death tests and non-death tests. What do I do?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md103',1,'']]],
  ['suite_20instead_20of_20individual_20tests_20to_20be_20named_20deathtest_20when_20it_20uses_20assert_5fdeath_184',['Why does googletest require the entire test suite, instead of individual tests, to be named *DeathTest when it uses ASSERT_DEATH?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md102',1,'']]],
  ['suite_20names_20and_20test_20names_20not_20contain_20underscore_185',['Why should test suite names and test names not contain underscore?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md82',1,'']]],
  ['suiteapiresolver_186',['SuiteApiResolver',['../structtesting_1_1internal_1_1_suite_api_resolver.html',1,'testing::internal']]],
  ['suites_20which_20share_20the_20same_20test_20fixture_20logic_20do_20i_20have_20to_20define_20a_20new_20test_20fixture_20class_20for_20each_20of_20them_20this_20seems_20pretty_20tedious_187',['I have several test suites which share the same test fixture logic, do I have to define a new test fixture class for each of them? This seems pretty tedious.',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md96',1,'']]],
  ['summary_20testpartresult_3a_3asummary_188',['summary {#TestPartResult::summary}',['../md_build_2__deps_2googletest-src_2docs_2reference_2testing.html#autotoc_md357',1,'']]],
  ['sumof5functor_189',['SumOf5Functor',['../structtesting_1_1gmock__more__actions__test_1_1_sum_of5_functor.html',1,'testing::gmock_more_actions_test']]],
  ['sumof6functor_190',['SumOf6Functor',['../structtesting_1_1gmock__more__actions__test_1_1_sum_of6_functor.html',1,'testing::gmock_more_actions_test']]],
  ['super_20vision_20into_20mock_20calls_191',['Gaining Super Vision into Mock Calls',['../md_build_2__deps_2googletest-src_2docs_2gmock__cook__book.html#autotoc_md165',1,'']]],
  ['support_20features_192',['Support features',['../md_build_2__deps_2googletest-src_2googletest_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md392',1,'Underlying library support features'],['../md_build_2dist_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md434',1,'Underlying library support features']]],
  ['support_20tt_20expect_5feq_20null_20ptr_20tt_20and_20tt_20assert_5feq_20null_20ptr_20tt_20but_20not_20tt_20expect_5fne_20null_20ptr_20tt_20and_20tt_20assert_5fne_20null_20ptr_20tt_193',['Why does googletest support &lt;tt&gt;EXPECT_EQ(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_EQ(NULL, ptr)&lt;/tt&gt; but not &lt;tt&gt;EXPECT_NE(NULL, ptr)&lt;/tt&gt; and &lt;tt&gt;ASSERT_NE(NULL, ptr)&lt;/tt&gt;?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md83',1,'']]],
  ['supported_20platforms_194',['Supported Platforms',['../md_build_2__deps_2googletest-src_2docs_2platforms.html',1,'Supported Platforms'],['../md_build_2__deps_2googletest-src_2_r_e_a_d_m_e.html#autotoc_md417',1,'Supported Platforms']]],
  ['suppress_20the_20memory_20leak_20messages_20on_20windows_195',['How do I suppress the memory leak messages on Windows?',['../md_build_2__deps_2googletest-src_2docs_2faq.html#autotoc_md106',1,'']]],
  ['suppressing_20test_20passes_196',['Suppressing test passes',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md70',1,'']]],
  ['suppressing_20the_20elapsed_20time_197',['Suppressing the Elapsed Time',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md71',1,'']]],
  ['suppressing_20utf_208_20text_20output_198',['Suppressing UTF-8 Text Output',['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md72',1,'']]],
  ['symbols_3a_199',['Symbols:',['../md_build_2__deps_2googletest-src_2googletest_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md393',1,'Exporting API symbols:'],['../md_build_2dist_2include_2gtest_2internal_2custom_2_r_e_a_d_m_e.html#autotoc_md435',1,'Exporting API symbols:']]],
  ['syntax_200',['Syntax',['../md_build_2__deps_2googletest-src_2docs_2gmock__for__dummies.html#autotoc_md209',1,'General Syntax'],['../md_build_2__deps_2googletest-src_2docs_2advanced.html#autotoc_md31',1,'Regular Expression Syntax']]],
  ['systems_201',['Systems',['../md_build_2__deps_2googletest-src_2docs_2platforms.html#autotoc_md223',1,'Build systems'],['../md_build_2__deps_2googletest-src_2_r_e_a_d_m_e.html#autotoc_md420',1,'Build Systems'],['../md_build_2__deps_2googletest-src_2docs_2platforms.html#autotoc_md221',1,'Operating systems'],['../md_build_2__deps_2googletest-src_2_r_e_a_d_m_e.html#autotoc_md418',1,'Operating Systems']]],
  ['systems_202',['Using GoogleTest from various build systems',['../md_build_2__deps_2googletest-src_2docs_2pkgconfig.html',1,'']]]
];
